// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsH9ksNs-BC9V1QPmzV9C9rq-BKBw0jZ4',
    appId: '1:868485232264:web:360aee799f6e106630113d',
    messagingSenderId: '868485232264',
    projectId: 'flutter-prep-55363',
    authDomain: 'flutter-prep-55363.firebaseapp.com',
    databaseURL: 'https://flutter-prep-55363-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-55363.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLqLQ0v6cdW_R49lXtH0RIa9FdWJlRAI',
    appId: '1:868485232264:android:978cf2d99a54b7f330113d',
    messagingSenderId: '868485232264',
    projectId: 'flutter-prep-55363',
    databaseURL: 'https://flutter-prep-55363-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-55363.appspot.com',
  );
}
